### ISSUE TITLE
Metadata editor -delete option and slowness in updating values

### ISSUE THREAD

**Issue by gayana06** [hopshadoop/hopsworks#183]
Delete metadata
--------------------------
In current implementation, when a raw metadata is updated with an empty string, does the elastic search drop it from its index? (Now the meta_data table contains the empty string)
How to tell elastic search to drop index for a raw metadata when it is deleting?

Slowness
------------------------
When a metadata is added or updated, a record is added to the hops.hdfs_metadata_log table in order to pick it up by elastic search. This table has a composite primary key(datasetid,inodeid,logical_time). For a certain inode, mutations are recorded by changing the only logical_time. But there is a max value for it which is 50, so if the number of mutations are exceeding 50 a log record will no longer added and tring 50 times to do it makes the delay.

Is 50 enough? any comments.

**Comment by evsav** [comment]
All metadata for all templates for a single inode is accumulated into a single string, which in turn is assigned to the elastic field EXTENDED_METADATA. It is rare that you would have a template with a single field i.e. ending up with a completely empty ext._meta. field in elastic.That being said it is fine having a few empty places into the final big string, as long as it doesn't become the norm.  It would only weaken the search functionality as one would not be able to match a text against an empty slot in the big string. Furthermore a document in the index contains several other fields (name, searchable, operation, etc) apart from the metadata field and represents an active file in the file system - with or without metadata, and all searches in turn are hitting multiple fields (name, description and metadata). The best you can do is handle empty fields either in the front end (not sending empty fields) or in the back end during the processing time, before persisting to the database; see StoreMetadataMessage where I skip empty multi-select values. You could do something similar.

On the other hand you could consider deleting documents from elastic only if the inode is removed from the file system, but still there is a high chance of loosing the sync'ing between hops - elastic due to wrong handling of inode ids. The current implementation handles this by reindexing deleted inodes and marking them as deleted (operation = 1) so effectively they are excluded from the search results; lucene also performs better when adding/updating documents incrementally rather than deleting (it would result in shard merging).

As for the hdfs_metadata_log I think the logical time does not increase if there is no repeating inode id. Since the rivers are purging hdfs_metadata_log, every new file operation would result in a logical_time=0 in most cases. I'm not 100% sure though, but again its a rare case where you would have more than 50 operations on a file (rename a file (remove-add) 25 times before indexing it?)

**Comment by jimdowling** [comment]
Thanks for the comments, @evsav. 
We have the outstanding problem of how to actually delete 'deleted files/metdata' from elastic, but we can leave that for a future version of Hopsworks.

**Comment by evsav** [comment]
The rivers don't support deleting documents as far as I know, so another service would be necessary to do curl requests to remove docs.

But instead of having this purging service it would be better in my opinion to have another which picks up active docs in bulk requests and transfers them to a fresh index. The old index then is removed. This avoids unnecessary shard merging/fragmentation etc. This would be my plan if it ever came to it. 

Deleting metadata results only in an empty metadata field - which is always present in elastic either empty or not. It's not related to deleting an inode - no?

**Comment by jimdowling** [comment]
Yes, we will need to have an "index compaction service" that creates new Elastic Indexes, copies the active docs in bulk requests to the new index. And then kills the rivers, shuts down the existing elastic index, and then starts the new elastic index and restarts the rivers, pointing them to the new index. For very large clusters (and shared Elastic servers), this will be hard.

**Comment by jimdowling** [comment]
Fixed with mahmoud's updates.
